name: CodeCov
on: [push, pull_request]

defaults:
    run:
        shell: bash -l {0}


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.8
          auto-activate-base: false
      - name: Install dependencies
        run: |
          conda install mpi4py setuptools
          pip install pyomo xpress cplex

      - name: set up mpi-sppy
        run: |
          git clone https://github.com/pyomo/mpi-sppy
          cd mpi-sppy && python setup.py develop

      - name: setup the program
        run: |
          python setup.py develop

      - name: Run tests and collect coverage
        run: pytest --cov app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

 