# simulate

name: simulate_boot tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
    run:
        shell: bash -l {0}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.9
          auto-activate-base: false
      - name: Install dependencies
        run: |
          conda install mpi4py setuptools
          pip install pyomo xpress cplex

      - name: set up mpi-sppy
        run: |
          git clone https://github.com/pyomo/mpi-sppy
          cd mpi-sppy && python setup.py develop

      - name: setup the program
        run: |
          python setup.py develop

      - name: run tests
        timeout-minutes: 100
        run: |
          cd bootsp/tests
          python test_simulate.py 
